name: Build and push Docker Image

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run:  aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c0u0j1e0
        env:  
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          
      - name: Build Docker Image
        run: docker build -t repositorydemo .

      - name: Tag Docker Image
        run: docker tag repositorydemo:latest public.ecr.aws/c0u0j1e0/repositorydemo:latest

      - name: Push Docker Image
        run: docker push public.ecr.aws/c0u0j1e0/repositorydemo:latest
