name: Build and push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
      - .github/workflows/terraform.yml
 
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run:  aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 236507926622.dkr.ecr.eu-central-1.amazonaws.com
        env:  
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          
      - name: Build Docker Image
        run: docker build -t repositorydemo .

      - name: Tag Docker Image
        run: docker tag repositorydemo:latest 236507926622.dkr.ecr.eu-central-1.amazonaws.com/repositorydemo:latest

      - name: Push Docker Image
        run: docker push 236507926622.dkr.ecr.eu-central-1.amazonaws.com/repositorydemo:latest
