name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/*.tf'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps: 
    - name: checkout repository 
      uses: actions/checkout@v2

    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: terraform init
      run: terraform init
      working-directory: ./terraform

    - name: terraform validate
      run: terraform validate
      working-directory: ./terraform
      
    - name: terraform plan
      run: terraform plan
      working-directory: ./terraform

    - name: terraform apply
      run: terraform apply -auto-approve
      working-directory: ./terraform

      
    
    

      

      
       
      
